### ISSUE TITLE
Computation Cost

### ISSUE THREAD

**Issue by ypwang61** [davidbrandfonbrener/color-filter-olmo#6]
### ❓ The question

Hi, thanks for your nice work on data scheduling on C4! And I'm very willing to develop based on your work! I would like to ask you how much computation cost you used in the main experiments, like how many GPU hours are needed for reproducing your experiments? Thanks a lot!

**Comment by davidbrandfonbrener** [comment]
Hi Yiping, thanks for your interest! 

Appendix D does out some of the calculations in FLOPs for the scale generalization experiments (training the 1.2b models). 

To reproduce e.g. the blue curve in Fig 1, on H100s it took ~4 hrs to train the prior and conditional models, ~110 hrs to do the scoring (but this is totally parallelizable), and then ~20 hrs to train the model (or 5 hrs on 4 GPUs using FSDP with olmo). So total 134hrs for one blue line. 

For the random baseline in Fig 1, it took 45 hrs on 4 GPUs using FSDP, so 180 GPU hrs. 

We also released data that can let you skip specific steps of the pipeline if you only want to reproduce specific parts of the results. Moreover, note that a lot of the computation can be re-used between experiments, e.g. to run different tau, you can use the same prior and conditional models, and thus re-use the cached scores and not have to redo that step.

Hope that helps!

**Comment by ypwang61** [comment]
Thanks for your quick and detailed reply! For the scoring time, do you mean that ~110hrs is for the current not fully parallelized version but it can be optimized or just using multiple GPU parallelly?

**Comment by davidbrandfonbrener** [comment]
I just mean that if you have 1 GPU is will take ~110 hours. If you had 110 GPUs, you could do it in 1 hour. 

The example slurm sweep [here](https://github.com/davidbrandfonbrener/color-filter-olmo/blob/7d26c7c097c06e0509f3f3e803b87bf05a8fea34/configs/sweeps/score-parallel.yaml#L20) launches 14 jobs corresponding to `prior` and `conditional_down`. So if you had 14 GPUs, it would take ~8 hrs. 

You can change the size of the chunk assigned to each worker in the sweep by setting `max_duration` and `data_start_step` in the config.
